### ISSUE TITLE
Query Subgraph Todos

### ISSUE THREAD

**Issue by jiqiang90** [subquery/query-subgraph#1]
**Goal**: This project aims to ensure that after a user migrates a Subgraph project to SubQuery, the same results are returned as the Subgraph query, without changing the user's frontend requests.

And here is a list of 

**Todos:**

- [x] Make configurable with input args, such as schema name 

- [x] Adjust query input/out structure ,eg remove `nodes`. Use `+connection +list` preset in https://postgraphile.org/postgraphile/next/connections#advice. But this will require to adjust `list` name, and identify other missing feature from list, and difference with subgraph. 

- [x] Add plugin for `id + blockrange`, support historical query,  should hide these two fields from query, and behaviour as we did in query v1.
- [x] Need to implement virtual id , same as https://github.com/subquery/subql/blob/main/packages/query/src/graphql/plugins/PgRowByVirtualIdPlugin.ts, in 
- [x] Fix `pgFakeConstraintsAutofixForeignKeyUniqueness` issue, it might relate with above _id issue
- [x] Pagination, change `offset` to `skip` ( We DO NOT need to change edge and cursor, not only supported by subgraph)

- [x] Add filter plugin (https://postgraphile.org/postgraphile/next/make-add-pg-table-condition-plugin), and change it to subgraph alike 
- [x] Add sort plugin(https://postgraphile.org/postgraphile/next/make-add-pg-table-order-by-plugin) , and and change it to subgraph alike
- [x] Add filter logical operators plugin
- [x] Metadata, we don't have block history, other fields seems can make a match 
- [x] Relations Query Plugin

**No need to do:**
- Aggragation
- Subscription

**Unkown**
- Query Complexity, not sure we need to match this complexity level with subgraph.
